import type { MacroDefinition } from './macro';

export const SAMPLE_MACROS: MacroDefinition[] = [
  {
    version: 1,
    meta: { key: 'launch_app_and_capture', name: 'Launch App And Capture', description: 'Má»Ÿ app, chá» vÃ i giÃ¢y, chá»¥p mÃ n hÃ¬nh, láº¥y app hiá»‡n táº¡i', tags: ['basic', 'screenshot', 'demo'] },
    inputs: { appName: { type: 'string', required: true, description: 'App package name to launch' } },
    target: { mode: 'single_device' },
    execution: { defaultTimeoutMs: 10000, maxRetries: 1, onError: 'stop' },
    steps: [
      { id: 'launch_1', type: 'launch_app', params: { appName: '{{appName}}' } },
      { id: 'wait_1', type: 'wait', params: { ms: 3000 } },
      { id: 'screen_1', type: 'screenshot', params: { saveToArtifact: true } },
      { id: 'current_1', type: 'get_current_app', params: {} },
    ],
  },
  {
    version: 1,
    meta: { key: 'input_text_demo', name: 'Input Text Demo', description: 'Má»Ÿ app, cháº¡m vÃ¹ng nháº­p, nháº­p text, chá»¥p mÃ n hÃ¬nh', tags: ['input', 'demo', 'ui'] },
    inputs: { appName: { type: 'string', required: true }, textValue: { type: 'string', required: true } },
    target: { mode: 'single_device' },
    execution: { defaultTimeoutMs: 12000, maxRetries: 1, onError: 'stop' },
    steps: [
      { id: 'launch_1', type: 'launch_app', params: { appName: '{{appName}}' } },
      { id: 'wait_1', type: 'wait', params: { ms: 2500 } },
      { id: 'tap_1', type: 'tap', params: { x: 0.5, y: 0.3 } },
      { id: 'wait_2', type: 'wait', params: { ms: 800 } },
      { id: 'input_1', type: 'input_text', params: { text: '{{textValue}}' } },
      { id: 'wait_3', type: 'wait', params: { ms: 1000 } },
      { id: 'screen_1', type: 'screenshot', params: { saveToArtifact: true } },
    ],
  },
  {
    version: 1,
    meta: { key: 'open_and_swipe_feed', name: 'Open And Swipe Feed', description: 'Má»Ÿ app vÃ  cuá»™n feed vÃ i láº§n Ä‘á»ƒ kiá»ƒm tra UI', tags: ['swipe', 'feed', 'demo'] },
    inputs: { appName: { type: 'string', required: true } },
    target: { mode: 'single_device' },
    execution: { defaultTimeoutMs: 15000, maxRetries: 1, onError: 'stop' },
    steps: [
      { id: 'launch_1', type: 'launch_app', params: { appName: '{{appName}}' } },
      { id: 'wait_1', type: 'wait', params: { ms: 3000 } },
      { id: 'swipe_1', type: 'swipe', params: { fromX: 0.5, fromY: 0.8, toX: 0.5, toY: 0.25 } },
      { id: 'wait_2', type: 'wait', params: { ms: 1200 } },
      { id: 'swipe_2', type: 'swipe', params: { fromX: 0.5, fromY: 0.8, toX: 0.5, toY: 0.25 } },
      { id: 'wait_3', type: 'wait', params: { ms: 1200 } },
      { id: 'screen_1', type: 'screenshot', params: { saveToArtifact: true } },
    ],
  },
  {
    version: 1,
    meta: { key: 'current_app_guard', name: 'Current App Guard', description: 'Kiá»ƒm tra app hiá»‡n táº¡i, náº¿u Ä‘Ãºng thÃ¬ chá»¥p mÃ n hÃ¬nh, sai thÃ¬ dá»«ng', tags: ['guard', 'conditional', 'validation'] },
    inputs: { appName: { type: 'string', required: true }, expectedPackage: { type: 'string', required: true } },
    target: { mode: 'single_device' },
    execution: { defaultTimeoutMs: 12000, maxRetries: 0, onError: 'stop' },
    steps: [
      { id: 'launch_1', type: 'launch_app', params: { appName: '{{appName}}' } },
      { id: 'wait_1', type: 'wait', params: { ms: 2500 } },
      { id: 'current_1', type: 'get_current_app', params: {} },
      {
        id: 'if_1',
        type: 'conditional',
        params: { left: '{{steps.current_1.appPackage}}', operator: 'equals', right: '{{expectedPackage}}' },
        then: [{ id: 'screen_ok', type: 'screenshot', params: { saveToArtifact: true } }],
        else: [{ id: 'stop_fail', type: 'stop', params: { reason: 'Current package does not match expectedPackage' } }],
      },
    ],
  },
  {
    version: 1,
    meta: { key: 'multi_device_launch_check', name: 'Multi Device Launch Check', description: 'Cháº¡y cÃ¹ng má»™t flow trÃªn nhiá»u thiáº¿t bá»‹', tags: ['multi-device', 'batch', 'monitoring'] },
    inputs: { appName: { type: 'string', required: true } },
    target: { mode: 'multi_device' },
    execution: { defaultTimeoutMs: 15000, maxRetries: 1, onError: 'continue' },
    steps: [
      { id: 'launch_1', type: 'launch_app', params: { appName: '{{appName}}' } },
      { id: 'wait_1', type: 'wait', params: { ms: 3000 } },
      { id: 'screen_1', type: 'screenshot', params: { saveToArtifact: true } },
      { id: 'current_1', type: 'get_current_app', params: {} },
    ],
  },
  {
    version: 1,
    meta: { key: 'approval_before_adb', name: 'Approval Before ADB', description: 'YÃªu cáº§u phÃª duyá»‡t trÆ°á»›c khi cháº¡y lá»‡nh ADB', tags: ['approval', 'adb', 'sensitive'] },
    inputs: { adbCommand: { type: 'string', required: true } },
    target: { mode: 'single_device' },
    execution: { defaultTimeoutMs: 20000, maxRetries: 0, onError: 'stop' },
    steps: [
      { id: 'approval_1', type: 'approval_checkpoint', params: { reason: 'ADB command requires manual approval' } },
      { id: 'adb_1', type: 'adb', params: { command: '{{adbCommand}}' }, policy: { requiresApproval: true } },
      { id: 'wait_1', type: 'wait', params: { ms: 1000 } },
      { id: 'screen_1', type: 'screenshot', params: { saveToArtifact: true } },
    ],
  },
  {
    version: 1,
    meta: { key: 'run_autox_with_approval', name: 'Run AutoX With Approval', description: 'Cháº¡y AutoX.js sau khi Ä‘Æ°á»£c phÃª duyá»‡t', tags: ['autox', 'approval', 'script'] },
    inputs: { filePath: { type: 'string', required: true } },
    target: { mode: 'single_device' },
    execution: { defaultTimeoutMs: 30000, maxRetries: 0, onError: 'stop' },
    steps: [
      { id: 'approval_1', type: 'approval_checkpoint', params: { reason: 'Execute AutoX.js requires manual review' } },
      { id: 'autox_1', type: 'run_autox', params: { filePath: '{{filePath}}' }, policy: { requiresApproval: true } },
      { id: 'wait_1', type: 'wait', params: { ms: 4000 } },
      { id: 'screen_1', type: 'screenshot', params: { saveToArtifact: true } },
    ],
  },
  {
    version: 1,
    meta: { key: 'settings_smoke_test', name: 'Settings Smoke Test', description: 'Má»Ÿ Settings, kiá»ƒm tra package Ä‘Ãºng, chá»¥p mÃ n hÃ¬nh', tags: ['settings', 'smoke-test', 'qa'] },
    inputs: {},
    target: { mode: 'single_device' },
    execution: { defaultTimeoutMs: 12000, maxRetries: 1, onError: 'stop' },
    steps: [
      { id: 'launch_1', type: 'launch_app', params: { appName: 'settings' } },
      { id: 'wait_1', type: 'wait', params: { ms: 2500 } },
      { id: 'current_1', type: 'get_current_app', params: {} },
      {
        id: 'if_1',
        type: 'conditional',
        params: { left: '{{steps.current_1.appPackage}}', operator: 'contains', right: 'settings' },
        then: [{ id: 'screen_ok', type: 'screenshot', params: { saveToArtifact: true } }],
        else: [{ id: 'stop_fail', type: 'stop', params: { reason: 'Settings app was not detected' } }],
      },
    ],
  },
  {
    version: 1,
    meta: { key: 'simple_form_fill_demo', name: 'Simple Form Fill Demo', description: 'Äiá»n 2 Ã´ nháº­p liá»‡u demo rá»“i chá»¥p mÃ n hÃ¬nh', tags: ['form', 'input', 'demo'] },
    inputs: { appName: { type: 'string', required: true }, firstValue: { type: 'string', required: true }, secondValue: { type: 'string', required: true } },
    target: { mode: 'single_device' },
    execution: { defaultTimeoutMs: 15000, maxRetries: 1, onError: 'stop' },
    steps: [
      { id: 'launch_1', type: 'launch_app', params: { appName: '{{appName}}' } },
      { id: 'wait_1', type: 'wait', params: { ms: 3000 } },
      { id: 'tap_1', type: 'tap', params: { x: 0.5, y: 0.28 } },
      { id: 'input_1', type: 'input_text', params: { text: '{{firstValue}}' } },
      { id: 'wait_2', type: 'wait', params: { ms: 700 } },
      { id: 'tap_2', type: 'tap', params: { x: 0.5, y: 0.42 } },
      { id: 'input_2', type: 'input_text', params: { text: '{{secondValue}}' } },
      { id: 'wait_3', type: 'wait', params: { ms: 1000 } },
      { id: 'screen_1', type: 'screenshot', params: { saveToArtifact: true } },
    ],
  },
  {
    version: 1,
    meta: { key: 'grouped_demo_sequence', name: 'Grouped Demo Sequence', description: 'Macro nhÃ³m step: má»Ÿ app, thao tÃ¡c nháº¹, chá»¥p mÃ n hÃ¬nh', tags: ['group', 'sequence', 'demo'] },
    inputs: { appName: { type: 'string', required: true } },
    target: { mode: 'single_device' },
    execution: { defaultTimeoutMs: 20000, maxRetries: 1, onError: 'stop' },
    steps: [
      {
        id: 'group_1',
        type: 'group',
        params: { name: 'launch_and_navigate' },
        steps: [
          { id: 'launch_1', type: 'launch_app', params: { appName: '{{appName}}' } },
          { id: 'wait_1', type: 'wait', params: { ms: 2500 } },
          { id: 'tap_1', type: 'tap', params: { x: 0.85, y: 0.92 } },
          { id: 'wait_2', type: 'wait', params: { ms: 1200 } },
          { id: 'swipe_1', type: 'swipe', params: { fromX: 0.5, fromY: 0.75, toX: 0.5, toY: 0.35 } },
        ],
      },
      { id: 'current_1', type: 'get_current_app', params: {} },
      { id: 'screen_1', type: 'screenshot', params: { saveToArtifact: true } },
    ],
  },
];
