-- Social engagement starter templates are registered in application code.
-- This migration is intentionally a no-op because the current macro schema
-- stores definitions in macro_versions, not macros.definition.
